### ISSUE TITLE
First "guide" link in README.md doesnt work

### ISSUE THREAD

**Issue by HarrisJT** [corenel/XPS9550-macOS#10]
Couldn't find the working link as I had no context.

https://www.tonymacx86.com/threads/guide-wip-dell-xps-15-9550-skylake-gtx960m-ssd-via-clover-uefi.192598/  is the broken link.

**Comment by corenel** [comment]
The thread on tonymacx86 is deleted, you can look at [this link](http://www.insanelymac.com/forum/topic/319766-dell-xps-9550-detailled-1011-guide/).

But that's for 10.11.6, you may look [this sierra guide](https://github.com/darkhandz/XPS15-9550-Sierra) or [this](https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Tutorial_10.12.md).
