### ISSUE TITLE
我的T460P i5-6440HQ 核显HD530 独显940mx 可以直接用你的这个吗？

### ISSUE THREAD

**Issue by cnyangyuan** [corenel/XPS9550-macOS#18]

**Comment by corenel** [comment]
@cnyangyuan 推荐先[用搜索引擎找](https://www.google.com/search?q=t460p+hackintosh)和您机型相同的配置文件。例如[这个](https://github.com/LER0ever/Hackintosh)。使用前请保证已经有相关预备知识。
