### ISSUE TITLE
How do I modify which file to adjust the keyboard layout

### ISSUE THREAD

**Issue by nick2834** [corenel/XPS9550-macOS#21]
How do I modify which file to adjust the keyboard layout, my computer configuration is the same as yours, but I am not used to this keyboard layout (Caps and Left-Ctrl)

**Comment by corenel** [comment]
You can set `Swap capslock and left control` from `true` to `false` in [this file](https://github.com/corenel/XPS9550-macOS/blob/master/CLOVER/kexts/Other/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist#L312-L313).
